### ISSUE TITLE
Can you help me to add  Object-c code?

### ISSUE THREAD

**Issue by mmm2006** [HackingGate/iOS13-WiFi-Info#2]
HI, I just encounter this issue too. But I don't know how to fix it in object-c format. Can you help me about this? thank you very much.

**Comment by HackingGate** [comment]
> HI, I just encounter this issue too. But I don't know how to fix it in object-c format. Can you help me about this? thank you very much.

Make sure location permission is granted before get current Wi-Fi info. 
It should not be hard in Objective-C.
