### ISSUE TITLE
NEHotspotConfiguration option

### ISSUE THREAD

**Issue by rawmean** [HackingGate/iOS13-WiFi-Info#3]
My app's functionality does not require location permission, so Apple rejects the app if I requires location permission. But my app does use NEHotspotConfiguration which is listed as the last bullet in WWDC slide.

Do you know how I can make that work?

**Comment by HackingGate** [comment]
> My app's functionality does not require location permission, so Apple rejects the app if I requires location permission. But my app does use NEHotspotConfiguration which is listed as the last bullet in WWDC slide.
> 
> Do you know how I can make that work?

If a Wi-Fi is configured by NEHotspotConfiguration. Location permission is not needed to get that Wi-Fi information.
