### ISSUE TITLE
information return in beta6.

### ISSUE THREAD

**Issue by mmm2006** [HackingGate/iOS13-WiFi-Info#5]
In beta6, I can get below information:
{
    BSSID = "00:00:00:00:00:00";
    SSID = WLAN;
    SSIDDATA = <574c414e>;
}

no nil return now. :)

**Comment by HackingGate** [comment]
@mmm2006  Are you still getting the issue now? I'm using iOS 13.1 beta1 and everything works fine.

**Comment by mmm2006** [comment]
HI, HackingGate, Do you mean there is no need to add permission checking in ios13.1, right? Thanks

**Comment by HackingGate** [comment]
@mmm2006 
You need location permission to get wifi information on iOS 13 and iOS 13.1. Apple add this limitation to protect user's privacy. I don't think Apple is going to change it back someday.
